main:
	g++ .\src\Assignment_1_lec_2\task_one_a.cpp .\src\imports.h -o src\Assignment_1_lec_2\task_one_a -I".\include" -L".\lib\x64" -lfreeglut -lopengl32 -lglu32
	g++ .\src\Assignment_1_lec_2\task_one_b.cpp .\src\imports.h -o src\Assignment_1_lec_2\task_one_b -I".\include" -L".\lib\x64" -lfreeglut -lopengl32 -lglu32
	g++ .\src\Assignment_1_lec_2\task_one_c.cpp .\src\imports.h -o src\Assignment_1_lec_2\task_one_c -I".\include" -L".\lib\x64" -lfreeglut -lopengl32 -lglu32
	g++ .\src\Assignment_1_lec_2\task_two_a.cpp .\src\imports.h -o src\Assignment_1_lec_2\task_two_a -I".\include" -L".\lib\x64" -lfreeglut -lopengl32 -lglu32
	g++ .\src\Assignment_1_lec_2\task_two_b.cpp .\src\imports.h -o src\Assignment_1_lec_2\task_two_b -I".\include" -L".\lib\x64" -lfreeglut -lopengl32 -lglu32
	g++ .\src\Assignment_1_lec_2\task_two_c.cpp .\src\imports.h -o src\Assignment_1_lec_2\task_two_c -I".\include" -L".\lib\x64" -lfreeglut -lopengl32 -lglu32
	.\src\Assignment_1_lec_2\task_one_a.exe
	.\src\Assignment_1_lec_2\task_one_b.exe
	.\src\Assignment_1_lec_2\task_one_c.exe
	.\src\Assignment_1_lec_2\task_two_a.exe
	.\src\Assignment_1_lec_2\task_two_b.exe
	.\src\Assignment_1_lec_2\task_two_c.exe