main:
	@echo "g++ .\src\Assignment_2_lec_3\task_one.cpp .\src\imports.h -o src\Assignment_2_lec_3\task_one -I".\include" -L".\lib\x64" -lfreeglut -lopengl32 -lglu32"
	@echo "g++ .\src\Assignment_2_lec_3\task_two_a.cpp .\src\imports.h -o src\Assignment_2_lec_3\task_two_a -I".\include" -L".\lib\x64" -lfreeglut -lopengl32 -lglu32"
	@echo "g++ .\src\Assignment_2_lec_3\task_two_b.cpp .\src\imports.h -o src\Assignment_2_lec_3\task_two_b -I".\include" -L".\lib\x64" -lfreeglut -lopengl32 -lglu32"
	@echo "g++ .\src\Assignment_2_lec_3\task_two_c.cpp .\src\imports.h -o src\Assignment_2_lec_3\task_two_c -I".\include" -L".\lib\x64" -lfreeglut -lopengl32 -lglu32"
	@echo "g++ .\src\Assignment_2_lec_3\task_two_d.cpp .\src\imports.h -o src\Assignment_2_lec_3\task_two_d -I".\include" -L".\lib\x64" -lfreeglut -lopengl32 -lglu32"
	@echo "g++ .\src\Assignment_2_lec_3\task_two_e.cpp .\src\imports.h -o src\Assignment_2_lec_3\task_two_e -I".\include" -L".\lib\x64" -lfreeglut -lopengl32 -lglu32"
	.\src\Assignment_2_lec_3\task_one.exe
	.\src\Assignment_2_lec_3\task_two_a.exe
	.\src\Assignment_2_lec_3\task_two_b.exe
	.\src\Assignment_2_lec_3\task_two_c.exe
	.\src\Assignment_2_lec_3\task_two_d.exe
	.\src\Assignment_2_lec_3\task_two_e.exe