main:
	@echo "g++ .\src\Assignment_3_lec_5\task_one.cpp .\src\imports.h -o src\Assignment_3_lec_5\task_one -I".\include" -L".\lib\x64" -lfreeglut -lopengl32 -lglu32"
	@echo "g++ .\src\Assignment_3_lec_5\task_two.cpp .\src\imports.h -o src\Assignment_3_lec_5\task_two -I".\include" -L".\lib\x64" -lfreeglut -lopengl32 -lglu32"
	@echo "g++ .\src\Assignment_3_lec_5\task_three.cpp .\src\imports.h -o src\Assignment_3_lec_5\task_three -I".\include" -L".\lib\x64" -lfreeglut -lopengl32 -lglu32"
	.\src\Assignment_3_lec_5\task_one.exe
	.\src\Assignment_3_lec_5\task_two.exe
	.\src\Assignment_3_lec_5\task_three.exe